### PR TITLE
fix dream template

### PR DESCRIPTION
**Pull request by robalmeister**

### CODE REVIEW

**Review by zitreF — APPROVED** [review]

**Review by qlnn — APPROVED** [review]

**Review by jedzius — APPROVED** [review]

**Review by kacorvixon1337 — APPROVED** [review]
approved.

**Review by Mefizo — APPROVED** [review]

**Comment by zitreF** [comment]
upgrade

**Comment by jedzius** [comment]
Podpisuje sie

**Comment by Mefizo** [comment]
To ja mefizo, prosze to skasowac ja tez sie zgadzam

**Review by qlnn — APPROVED** [review]

**Comment by qlnn** [comment]
Conversation 4
[ Commits 1](https://github.com/DreamPoland/dream-template/pull/69/commits)
[ Checks 0](https://github.com/DreamPoland/dream-template/pull/69/checks)
[ Files changed 43](https://github.com/DreamPoland/dream-template/pull/69/files)
Conversation
robalmeister
Donacja
[robalmeister](https://github.com/robalmeister) commented [3 hours ago](https://github.com/DreamPoland/dream-template/pull/69#issue-1699195571)
No description provided.

@robalmeister
[fix dream template](https://github.com/DreamPoland/dream-template/pull/69/commits/723210985d49f0e0d7603419cb6dec18a4e21fcf)
[7232109](https://github.com/DreamPoland/dream-template/pull/69/commits/723210985d49f0e0d7603419cb6dec18a4e21fcf)
[zitreF](https://github.com/zitreF)
zitreF approved these changes [3 hours ago](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415950767)
[qlnn](https://github.com/qlnn)
qlnn approved these changes [3 hours ago](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415950787)
[jedzius](https://github.com/jedzius)
jedzius approved these changes [2 hours ago](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415954884)
[kacorvixon1337](https://github.com/kacorvixon1337)
kacorvixon1337 approved these changes [2 hours ago](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415960047)
Donacja
[kacorvixon1337](https://github.com/kacorvixon1337) left a comment
approved.

kacorvixon1337, [Mefizo](https://github.com/Mefizo), and zitreF reacted with rocket emoji
Mefizo
Mefizo approved these changes [1 hour ago](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415964127)
@zitreF
Donacja
[zitreF](https://github.com/zitreF) commented [1 hour ago](https://github.com/DreamPoland/dream-template/pull/69#issuecomment-1537544217)
upgrade

@jedzius
Donacja
[jedzius](https://github.com/jedzius) commented [1 hour ago](https://github.com/DreamPoland/dream-template/pull/69#issuecomment-1537545726)
Podpisuje sie

@Mefizo
Donacja
[Mefizo](https://github.com/Mefizo) commented [50 minutes ago](https://github.com/DreamPoland/dream-template/pull/69#issuecomment-1537548149)
To ja mefizo, prosze to skasowac ja tez sie zgadzam

[qlnn](https://github.com/qlnn)
qlnn approved these changes [now](https://github.com/DreamPoland/dream-template/pull/69#pullrequestreview-1415971747)

**Pull request closed without merging**
